exclude: |
    (?x)^(
      .*/migrations/.*|
      .*/settings/.*|
      .*/venv/.*|
      .*/.venv/>*|
    )$

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
            types: [python]
            files: ^backend/
            stages: [pre-commit]

          - id: check-yaml
            files: \.ya?ml$
            stages: [pre-commit]

          - id: debug-statements
            types: [python]
            files: ^backend/
            stages: [pre-commit]

    - repo: https://github.com/psf/black
      rev: 24.10.0
      hooks:
          - id: black
            args: [--line-length=88]
            files: ^backend/
            stages: [pre-commit]

    - repo: https://github.com/hhatto/autopep8
      rev: v2.3.1
      hooks:
          - id: autopep8
            files: ^backend/
            stages: [pre-commit]

    - repo: https://github.com/PyCQA/flake8
      rev: 7.1.1
      hooks:
          - id: flake8
            args: ["--exclude=src/settings/*,*/migrations/*, */destination_mapper.py", "--ignore=F403,F401,F405,W503", "--max-line-length=88"]
            files: ^backend/
            stages: [pre-commit]
